SquashNiagara/SquashNiagara/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using SquashNiagara.Data;
using SquashNiagara.Models;
using Microsoft.AspNetCore.Identity;

namespace SquashNiagara.Controllers
{
    public class TeamsController : Controller
    {
        private readonly SquashNiagaraContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TeamsController(SquashNiagaraContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Teams
        public async Task<IActionResult> Index(int? SeasonID, string DivisionID)
        {
            if (User.IsInRole("Captain") || User.IsInRole("User"))
            {
                var email = User.Identity.Name;
                var player = _context.Players
                .Include(t => t.Team)
                .Include(t => t.Position)
                .FirstOrDefault(m => m.Email == User.Identity.Name);
                if (player.TeamID.HasValue)
                {
                    return RedirectToAction("Details", new { id = player.TeamID }); 
                }
                else
                {
                    return View("NoTeamAssigned");
                }
               

            }

            //var teams = from t in _context.Teams
            //    .Include(t => t.Captain)
            //    .Include(t => t.Venue)
            //            where t.ID == 0
            //            select t;

            

            var teams = from t in _context.Teams
                    .Include(t => t.Captain)
                    .Include(t => t.Venue)
                    where t.ID == 0
                    select t;

            if (SeasonID.HasValue && DivisionID != null)
            {
                var TeamsIDS = (from t in _context.SeasonDivisionTeams
                               where t.SeasonID == SeasonID && t.DivisionID == Convert.ToInt32(DivisionID)
                               select t.TeamID).ToList();

                teams = _context.Teams
                    .Where(t => TeamsIDS.Contains(t.ID))
                    .Include(t => t.Captain)
                    .Include(t => t.Venue);


                //teams.ToListAsync().
            }
            //else
            //{
            //    teams = from t in _context.Teams
            //        .Include(t => t.Captain)
            //        .Include(t => t.Venue)
            //                where t.ID == 0
            //                select t;
            //}

            PopulateDropDownListSeason();
            ViewData["DivisionID"] = from d in _context.Divisions
                                     select d;

            return View(await teams.ToListAsync());
        }

        public IActionResult NoTeamAssigned()
        {
            return View();
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .Include(t => t.Captain)
                .Include(t => t.Venue)
                .FirstOrDefaultAsync(m => m.ID == id);

            var dQuery = from d in _context.Players
                         orderby d.FullName
                         where d.TeamID == id
                         select d;
            
            if (team == null)
            {
                return NotFound();
            }

            //var dQuery = _context.Players
             //   .FirstOrDefault(p => p.TeamID == id);

            ViewData["TeamPlayers"] = dQuery;

            return View(team);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            //ViewData["CaptainID"] = new SelectList(_context.Players, "ID", "Email");
            PopulateDropDownListCaptain();
            PopulateDropDownListVenue();
            PopulateDropDownListSeason();
            PopulateDropDownListDivision();
            //ViewData["VenueID"] = new SelectList(_context.Venues, "ID", "Name");
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name, CaptainID, VenueID, Profile")] Team team,  
            IFormFile thePicture, int SeasonID, int DivisionID)
        {
            bool error = false;

            if (SeasonID == 0)
            {
                if (DivisionID == 0)
                {
                    ModelState.AddModelError("", "Please, select a Season and Division");
                    error = true;
                } else
                {
                    ModelState.AddModelError("", "Please, select a Season");
                    error = true;
                }
            } else if (SeasonID == 0)
            {
                ModelState.AddModelError("", "Please, select a Division");
                error = true;
            }

            if (error == true)
            {
                PopulateDropDownListCaptain();
                PopulateDropDownListVenue();
                PopulateDropDownListSeason();
                PopulateDropDownListDivision();
                return View();
            }

            try {
                if (ModelState.IsValid)
                {
                    if (thePicture != null)
                    {
                        string mimeType = thePicture.ContentType;
                        long fileLength = thePicture.Length;
                        if (!(mimeType == "" || fileLength == 0))
                        {
                            if (mimeType.Contains("image"))
                            {
                                using (var memoryStream = new MemoryStream())
                                {
                                    await thePicture.CopyToAsync(memoryStream);
                                    team.imageContent = memoryStream.ToArray();
                                }
                                team.imageMimeType = mimeType;
                                team.imageFileName = thePicture.FileName;
                            }
                        }
                    }

                    _context.Add(team);
                    await _context.SaveChangesAsync();

                    int teamID = _context.Teams.FirstOrDefault(d => d.Name == team.Name).ID;
                    
                    var checkExistSeasonDivisionTeam = _context.SeasonDivisionTeams.FirstOrDefault(d => d.SeasonID == SeasonID && d.DivisionID == DivisionID && d.TeamID == teamID);
                    if (checkExistSeasonDivisionTeam == null)
                    {
                        SeasonDivisionTeam seasonDivisionTeam = new SeasonDivisionTeam
                        {
                            SeasonID = SeasonID,
                            DivisionID = DivisionID,
                            TeamID = teamID
                        };
                        _context.SeasonDivisionTeams.Add(seasonDivisionTeam);
                        _context.SaveChanges();
                    }

                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception err)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator." + err.ToString());
            }
            //ViewData["CaptainID"] = new SelectList(_context.Players, "ID", "Email", team.CaptainID);
            PopulateDropDownListCaptain(team);
            PopulateDropDownListVenue(team);
            //ViewData["VenueID"] = new SelectList(_context.Venues, "ID", "Name", team.VenueID);
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            PopulateDropDownListCaptain(team);
            PopulateDropDownListVenue(team);
           // ViewData["VenueID"] = new SelectList(_context.Venues, "ID", "Name", team.VenueID);
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, /*[Bind("ID, Name, CaptainID, VenueID, Profile")]*/ Team team, string chkRemoveImage, IFormFile thePicture)
        {
            //Add Role to captain - BEGIN
            var userToUpdate = await _context.Players
                .SingleOrDefaultAsync(d => d.TeamID == id && d.ID == team.CaptainID);

            var user = await _userManager.FindByEmailAsync(userToUpdate.Email);

            var newRoleToCaptain = _userManager.AddToRoleAsync(user, "Captain");
            //Add Role to captain - END

            var teamToUpdate = await _context.Teams
                .SingleOrDefaultAsync(d => d.ID == id);

            if (teamToUpdate == null)
            {
                return NotFound();
            }
            //if (team.CaptainID == 0)
            //{
            //    team.CaptainID = null;
            //}

SquashNiagara/SquashNiagara/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SquashNiagara.Data;
using SquashNiagara.Models;

namespace SquashNiagara.Controllers
{
    public class VenuesController : Controller
    {
        private readonly SquashNiagaraContext _context;

        public VenuesController(SquashNiagaraContext context)
        {
            _context = context;
        }

        // GET: Venues
        public async Task<IActionResult> Index()
        {
            return View(await _context.Venues.ToListAsync());
        }

        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venues
                .FirstOrDefaultAsync(m => m.ID == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // GET: Venues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Address,City,Province,PostalCode")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venues.FindAsync(id);
            if (venue == null)
            {
                return NotFound();
            }
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Address,City,Province,PostalCode")] Venue venue)
        {
            if (id != venue.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venues
                .FirstOrDefaultAsync(m => m.ID == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venue = await _context.Venues.FindAsync(id);
            _context.Venues.Remove(venue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return _context.Venues.Any(e => e.ID == id);
        }
    }
}

SquashNiagara/SquashNiagara/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SquashNiagara</title>
    <style>
        .imgCenter {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SquashNiagara</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home<i class="fas fa-user"></i></a></li>
        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin <i class="fas fa-user"></i><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Seasons" asp-action="Index">Seasons</a></li>
                                    <li><a asp-area="" asp-controller="Divisions" asp-action="Index">Divisions</a></li>
                                    <li><a asp-area="" asp-controller="Teams" asp-action="Index">Teams</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-area="" asp-controller="Players" asp-action="Index">Players</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-area="" asp-controller="Fixtures" asp-action="Index">Fixtures</a></li>
                                    <li><a asp-area="" asp-controller="Venues" asp-action="Index">Venues</a></li>
                                    <li class="divider"></li>
                                    <li><a asp-area="Identity" asp-page="/Account/Register">Register Users</a></li>
                                </ul>
                            </li>
                        }
                        else if (User.IsInRole("Captain"))
                        {
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Profiles<i class="fas fa-user"></i><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Players" asp-action="Index">My Profile</a></li>
                                    <li><a asp-area="" asp-controller="Teams" asp-action="Index">My Team</a></li>
                                    <li><a asp-area="" asp-controller="Fixtures" asp-action="Index">Fixtures</a></li>
                                </ul>
                            </li>
                        }
                        else if (User.IsInRole("User"))
                        {
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Profiles<i class="fas fa-user"></i><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a asp-area="" asp-controller="Players" asp-action="Index">My Profile</a></li>
                                    <li><a asp-area="" asp-controller="Teams" asp-action="Index">My Team</a></li>
                                </ul>
                            </li>
                        }
                    }

                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Squash Results <i class="far fa-list-alt"></i><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Home" asp-action="TeamRanking">Team Ranking</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="PlayerRanking">Player Ranking</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="Standings">Standings</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="Violation">Historical Reports</a></li>
                        </ul>
                    </li>
                    @*<li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Squash Schedule <i class="far fa-calendar-alt"></i><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Fixtures" asp-action="Index">Men's Schedule</a></li>
                            <li><a asp-area="" asp-controller="Fixtures" asp-action="Index">Women's Schedule</a></li>
                        </ul>
                    </li>*@
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Schedule">Squash Schedule</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Squash Rules/News <i class="fas fa-tasks"></i><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Home" asp-action="Rules">League Constitution</a></li>
                            <li><a asp-area="" asp-controller="Home" asp-action="News">News <i class="far fa-newspaper"></i></a></li>
                        </ul>
                    </li>
                    @*<li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">League Rules <i class="fas fa-tasks"></i><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a asp-area="" asp-controller="Home" asp-action="Rules">League Constitution</a></li>
            </ul>
        </li>*@
                    @*<li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Document <i class="fas fa-file"></i><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Score Sheet</a></li>
            </ul>
        </li>*@
                    @*<li><a asp-area="" asp-controller="Home" asp-action="News">News <i class="far fa-newspaper"></i></a></li>*@
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    @*<partial name="_CookieConsentPartial" />*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SquashNiagara</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>