SquashNiagara/SquashNiagara/Models/Fixture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SquashNiagara.Models
{
    public class Fixture
    {
        public Fixture()
        {
            Matches = new HashSet<Match>();
        }

        public int ID { get; set; }

        [Display(Name = "Season")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select the Division.")]
        public int SeasonID { get; set; }
        public Season Season { get; set; }

        [Display(Name = "Division")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select the Division.")]
        public int DivisionID { get; set; }
        public Division Division { get; set; }

        [Display(Name = "(H)-Team")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select the Home Team.")]
        public int HomeTeamID { get; set; }
        public Team HomeTeam { get; set; }

        [Display(Name = "(A)-Team")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select the Away Team.")]
        public int AwayTeamID { get; set; }
        public Team AwayTeam { get; set; }

        [Required(ErrorMessage = "Date is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Time is required")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime Time { get; set; }

        [Required(ErrorMessage = "Date is required")]
        [Display(Name = "Venue")]
        public int VenueID { get; set; }
        public Venue Venue { get; set; }

        [Display(Name = "(H)-Score")]
        [Range(0, 5, ErrorMessage = "Score have to be beteween 0 and 5")]
        [RegularExpression("^\\d{1}$", ErrorMessage = "Please enter a valid number")]
        public Int16? HomeTeamScore { get; set; }

        [Display(Name = "(A)-Score")]
        [Range(0, 5, ErrorMessage = "Score have to be beteween 0 and 5")]
        [RegularExpression("^\\d{1}$", ErrorMessage = "Please enter a valid number")]
        public Int16? AwayTeamScore { get; set; }

        [Display(Name = "(H)-Bonus")]
        [Range(0, 1, ErrorMessage = "Bonus have to be 0 or 1")]
        [RegularExpression(@"^\d+(.\d{1,2})?$", ErrorMessage = "Please enter a valid number")]
        public double? HomeTeamBonus { get; set; }

        [Display(Name = "(A)-Bonus")]
        [Range(0, 1, ErrorMessage = "Bonus have to be 0, 0.5 or 1")]
        [RegularExpression(@"^\d+(.\d{1,2})?$", ErrorMessage = "Please enter a valid number")]
        public double? AwayTeamBonus { get; set; }

        [ScaffoldColumn(false)]
        public int? CaptainResultID { get; set; }
        public virtual Player CaptainResult { get; set; }

        [ScaffoldColumn(false)]
        public int? CaptainApproveID { get; set; }
        public virtual Player CaptainApprove { get; set; }

        [ScaffoldColumn(false)]
        public bool Approved { get; set; }

        public virtual ICollection<Match> Matches { get; set; }
    }
}

SquashNiagara/SquashNiagara/Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SquashNiagara.Data;
using SquashNiagara.Models;
using SquashNiagara.ViewModels;
using SquashNiagaraLib;

namespace SquashNiagara.Controllers
{
    public class MatchesController : Controller
    {
        private readonly SquashNiagaraContext _context;

        public MatchesController(SquashNiagaraContext context)
        {
            _context = context;
        }

        // GET: Matches
        public async Task<IActionResult> Index()
        {
            var squashNiagaraContext = _context.Matches.Include(m => m.AwayPlayer).Include(m => m.Fixture).Include(m => m.HomePlayer);
            return View(await squashNiagaraContext.ToListAsync());
        }

        // GET: Matches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var match = await _context.Matches
                .Include(m => m.AwayPlayer)
                .Include(m => m.Fixture)
                .Include(m => m.HomePlayer)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (match == null)
            {
                return NotFound();
            }

            return View(match);
        }

        // GET: Matches/Create
        public async Task<IActionResult> Create(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            //var fixture = await _context.Fixtures.FindAsync(id);
            var fixture = await _context.Fixtures
                .Include(f => f.AwayTeam)
                .Include(f => f.CaptainApprove)
                .Include(f => f.CaptainResult)
                .Include(f => f.Division)
                .Include(f => f.HomeTeam)
                .Include(f => f.Season)
                .Include(f => f.Venue)
                .FirstOrDefaultAsync(m => m.ID == id);

            //int nPositions = 4;
            int nPositions = _context.Divisions.FirstOrDefault(d => d.ID == fixture.DivisionID).PositionNo;

            if (fixture == null)
            {
                return NotFound();
            }

            FixtureMatchVM fixtureMatch = new FixtureMatchVM();
            fixtureMatch.Fixture = fixture;

            for (int i = 0; i < nPositions; i++)
            {
                Match match = new Match();
                fixtureMatch.Matches.Add(match);
            }

            //.FirstOrDefaultAsync(m => m.ID == fixture.DivisionID);

            var dQueryHome = from d in _context.Players
                         orderby d.FirstName, d.LastName
                         where d.TeamID == fixture.HomeTeamID || d.ID == 1
                         select d;

            var dQueryAway = from d in _context.Players
                             orderby d.FirstName, d.LastName
                             where d.TeamID == fixture.AwayTeamID || d.ID == 1
                             select d;

            var homeTeam = _context.Teams.FirstOrDefault(t => t.ID == fixture.HomeTeamID);
            var awayTeam = _context.Teams.FirstOrDefault(t => t.ID == fixture.AwayTeamID);

            ViewData["HomeTeam"] = homeTeam;
            ViewData["AwayTeam"] = awayTeam;

            ViewData["AwayPlayerID"] = new SelectList(dQueryAway, "ID", "FullName");
            ViewData["HomePlayerID"] = new SelectList(dQueryHome, "ID", "FullName");
            ViewData["nPositions"] = nPositions;
            return View(fixtureMatch);
        }

        // POST: Matches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FixtureMatchVM fixtureMatch, string Bonus)
        {
            //get the number of the positions for the division;
            int nPositions = _context.Divisions.FirstOrDefault(d => d.ID == fixtureMatch.Fixture.DivisionID).PositionNo;
            if (Bonus == "Home")
            {
                fixtureMatch.Fixture.HomeTeamBonus = 1d;
                fixtureMatch.Fixture.AwayTeamBonus = 0d;
            } else if (Bonus == "Away")
            {
                fixtureMatch.Fixture.HomeTeamBonus = 0d;
                fixtureMatch.Fixture.AwayTeamBonus = 1d;
            }
            else if (Bonus == "Tie")
            {
                fixtureMatch.Fixture.HomeTeamBonus = 0.5d;
                fixtureMatch.Fixture.AwayTeamBonus = 0.5d;
            }

            try
            {
                if (ModelState.IsValid)
                {
                    //Get the fixture from model FixtureMatch
                    Fixture fixture = fixtureMatch.Fixture;
                    fixture.HomeTeamScore = 0;
                    fixture.AwayTeamScore = 0;
                    for (int n = 0; n < nPositions; n++)
                    {
                        if (fixtureMatch.Matches[n].HomePlayerScore > fixtureMatch.Matches[n].AwayPlayerScore)
                            fixture.HomeTeamScore += 1;
                        else if (fixtureMatch.Matches[n].HomePlayerScore < fixtureMatch.Matches[n].AwayPlayerScore)
                            fixture.AwayTeamScore += 1;
                        else
                        {
                            ModelState.AddModelError("Score error", "No results can be blank");
                            return View(fixtureMatch);
                        }

                        //Save the fixture in the DB
                        if (User.IsInRole("Captain"))
                        {
                            fixture.CaptainResultID = _context.Players.FirstOrDefault(p => p.Email == User.Identity.Name).ID;
                        }
                        _context.Update(fixture);
                    }

                    //Loop trough the matches to get the matches results and add in the DB
                    for (int i = 0; i < nPositions; i++)
                    {
                        //Capture the result of the match and save in the database
                        Match match = fixtureMatch.Matches[i];
                        match.PositionID = _context.Positions.FirstOrDefault(d => d.Name.Contains((i + 1).ToString())).ID;

                        _context.Add(match);

                        //Add in the DB the PlayerPosition for home player
                        PlayerPosition playerPositionHome = new PlayerPosition
                        {
                            PlayerID = match.HomePlayerID,
                            MatchID = match.ID,
                            PositionID = _context.Positions.FirstOrDefault(d => d.Name.Contains((i + 1).ToString())).ID,
                        };

                        _context.Add(playerPositionHome);

                        //Add in the DB the PlayerPosition for away player
                        PlayerPosition playerPositionAway = new PlayerPosition
                        {
                            PlayerID = match.AwayPlayerID,
                            MatchID = match.ID,
                            PositionID = _context.Positions.FirstOrDefault(d => d.Name.Contains((i + 1).ToString())).ID,
                        };
                        _context.Add(playerPositionAway);
                    }

                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Fixtures");
                }
            }
            catch (DbUpdateException err)
            {
                if (err.InnerException.Message.Contains("IX_Matches_FixtureID_HomePlayerID_AwayPlayerID"))
                {
                    ModelState.AddModelError("Player error", "One player cannot play two matches in the same fixture");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save result. Report this error to the team");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save result. Report this error to the team");
            }
            finally
            {
                var dQueryHome = from d in _context.Players
                                 orderby d.FirstName, d.LastName
                                 where d.TeamID == fixtureMatch.Fixture.HomeTeamID || d.ID == 1
                                 select d;

                var dQueryAway = from d in _context.Players
                                 orderby d.FirstName, d.LastName
                                 where d.TeamID == fixtureMatch.Fixture.AwayTeamID || d.ID == 1
                                 select d;

                ViewData["AwayPlayerID"] = new SelectList(dQueryAway, "ID", "FullName");
                ViewData["HomePlayerID"] = new SelectList(dQueryHome, "ID", "FullName");
                ViewData["nPositions"] = nPositions;
            }
            
            return View(fixtureMatch);
        }

        // GET: Matches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            //var fixture = await _context.Fixtures.FindAsync(id);
            var fixture = await _context.Fixtures
                .Include(f => f.AwayTeam)
                .Include(f => f.CaptainApprove)
                .Include(f => f.CaptainResult)
                .Include(f => f.Division)
                .Include(f => f.HomeTeam)
                .Include(f => f.Season)
                .Include(f => f.Venue)
                .FirstOrDefaultAsync(m => m.ID == id);

            var matches = _context.Matches

SquashNiagara/SquashNiagara/Views/Fixtures/AddResult.cshtml
@model SquashNiagara.Models.Fixture

@{
    ViewData["Title"] = "Edit";
}
@{  

    var matches = ViewData["TheMatch"];
}
<h2>Add Result</h2>

<h4>Fixture</h4>
<hr />

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Season)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Season.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Division)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Division.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomeTeam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeTeam.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AwayTeam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AwayTeam.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Venue.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomeTeamScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeTeamScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AwayTeamScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AwayTeamScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomeTeamBonus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomeTeamBonus)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AwayTeamBonus)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AwayTeamBonus)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.CaptainApprove.Email)
        </dd>
    </dl>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddResult">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="SeasonID" />
            <input type="hidden" asp-for="DivisionID" />
            <input type="hidden" asp-for="HomeTeamID" />
            <input type="hidden" asp-for="AwayTeamID" />
            <input type="hidden" asp-for="Date" />
            <input type="hidden" asp-for="Time" />
            <input type="hidden" asp-for="VenueID" />
            <input type="hidden" asp-for="CaptainResultID" />
            <input type="hidden" asp-for="CaptainApproveID" />
            <div class="form-group">
                <label asp-for="HomeTeamScore" class="control-label"></label>
                <input asp-for="HomeTeamScore" class="form-control" />
                <span asp-validation-for="HomeTeamScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwayTeamScore" class="control-label"></label>
                <input asp-for="AwayTeamScore" class="form-control" />
                <span asp-validation-for="AwayTeamScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeTeamBonus" class="control-label"></label>
                <input asp-for="HomeTeamBonus" class="form-control" />
                <span asp-validation-for="HomeTeamBonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AwayTeamBonus" class="control-label"></label>
                <input asp-for="AwayTeamBonus" class="form-control" />
                <span asp-validation-for="AwayTeamBonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                @matches
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SquashNiagara/SquashNiagara/Views/Fixtures/Details.cshtml
@model SquashNiagara.Models.Fixture

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div class="row">
    <div class="col-md-4">
        <h4>Fixture</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Season)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Season.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Division)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Division.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.HomeTeam)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.HomeTeam.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AwayTeam)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AwayTeam.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Time)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Venue)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Venue.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.HomeTeamScore)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.HomeTeamScore)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AwayTeamScore)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AwayTeamScore)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.HomeTeamBonus)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.HomeTeamBonus)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AwayTeamBonus)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AwayTeamBonus)
            </dd>
            <dt>
                Result added by
            </dt>
            <dd>
                @if (Model.CaptainResultID.HasValue)
                {
                    @Html.DisplayFor(model => model.CaptainResult.FullName)
                }
                else if (Model.HomeTeamScore.HasValue || Model.AwayTeamScore.HasValue)
                {
                    @:Admin
                }
            </dd>
            <dt>
                Result approved by
            </dt>
            <dd>
                @if (Model.CaptainApproveID.HasValue)
                {
                    @Html.DisplayFor(model => model.CaptainApprove.FullName)
                }
                else if (Model.Approved == true)
                {
                    @:Admin
                }
            </dd>
        </dl>
    </div>
    <div class="col-md-8">
        <h4>Matches</h4>
        <hr />
        <div class="row">
            <div class="col-md-2">

            </div>
            <div class="col-md-2" style="text-align:center">
                <strong>@Html.DisplayFor(model => model.HomeTeam.Name)</strong>
            </div>
            <div class="col-md-1">

            </div>
            <div class="col-md-1">

            </div>
            <div class="col-md-1">

            </div>
            <div class="col-md-2" style="text-align:center">
                <strong>@Html.DisplayFor(model => model.AwayTeam.Name)</strong>
            </div>
        </div>
        <br />
        @foreach (Match match in Model.Matches)
        {
            <div class="row">
                <div class="col-md-2">
                    @Html.DisplayFor(m => match.Position.Name)
                </div>
                <div class="col-md-2">
                    @Html.DisplayFor(m => match.HomePlayer.FullName)
                </div>
                <div class="col-md-1">
                    @Html.DisplayFor(m => match.HomePlayerScore)
                </div>
                <div class="col-md-1">
                    X
                </div>
                <div class="col-md-1">
                    @Html.DisplayFor(m => match.AwayPlayerScore)
                </div>
                <div class="col-md-2">
                    @Html.DisplayFor(m => match.AwayPlayer.FullName)
                </div>
            </div>
            <div class="row">
                <hr />
            </div>

        }
    </div>
</div>
<div>
    <a asp-controller="Matches" asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SquashNiagara/SquashNiagara/Views/Fixtures/Index.cshtml
@model IEnumerable<SquashNiagara.Models.Fixture>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Squash Niagara Fixtures</h1>

@if (User.Identity.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <p>
            <a asp-action="Create" class="btn btn-primary btn-sm">Create New</a>
            <a asp-action="ImportFixtures" class="btn btn-default btn-sm">Import Fixtures</a>
        </p>
    }

}

<form asp-action="Index">
    <div class="form-inline">
        <div class="row ">
            <div class="form-group col-sm-10 ">
                @foreach (Division i in @ViewBag.DivisionID)
                {
                    if (User.IsInRole("Captain"))
                    {
                        if (ViewBag.CaptainDivision == i.ID)
                        {
                            <button name="DivisionID" value="@i.ID" class="btn btn-primary btn-sm">@i.Name</button>
                        }
                    }
                    else
                    {
                        <button name="DivisionID" value="@i.ID" class="btn btn-primary btn-sm">@i.Name</button>
                    }

                    @*<a asp-action="Index" asp-route-id="@i.ID" class="btn btn-primary btn-sm">@i.Name</a>
                        <input type="submit" name="divisionButton" value="@i.Name" id="@i.ID" class="btn btn-default" />*@
                }
            </div>
            <div class="form-group col-sm-2 ">
                <label class="col-sm-5" style="margin-left:10px;">Season</label>
                <div class="col-sm-7">@Html.DropDownList("SeasonID", (SelectList)ViewBag.SeasonID, new { @class = "form-control input-sm", onchange = "this.form.submit();" })</div>

            </div>
        </div>
    </div>
</form>
<br /><br />
<table id="indxFix" class="table table-striped table-bordered nowrap" style="width: 100%">
    <thead>
        <tr>
            <th>
                <small> @Html.DisplayNameFor(model => model.Date)</small>
            </th>
            <th>
                <small> @Html.DisplayNameFor(model => model.Time)</small>
            </th>
            <th>
                <small>  @Html.DisplayNameFor(model => model.HomeTeam)</small>
            </th>
            <th class="text-nowrap">
                <small>  @Html.DisplayNameFor(model => model.HomeTeamScore)</small>
            </th>
            <th class="text-nowrap">
                <small>  @Html.DisplayNameFor(model => model.AwayTeamScore)</small>
            </th>
            <th>
                <small> @Html.DisplayNameFor(model => model.AwayTeam)</small>
            </th>
            <th>
                <small>  @Html.DisplayNameFor(model => model.Venue)</small>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            bool homeWin = false;
            bool awayWin = false;
        }
        @foreach (var item in Model)
        {
            if ((@Convert.ToDouble(item.HomeTeamScore) + @Convert.ToDouble(item.HomeTeamBonus)) > (@Convert.ToDouble(item.AwayTeamScore) + @Convert.ToDouble(item.AwayTeamBonus)))
            {
                homeWin = true;
            }
            else if ((@Convert.ToDouble(item.HomeTeamScore) + @Convert.ToDouble(item.HomeTeamBonus)) < (@Convert.ToDouble(item.AwayTeamScore) + @Convert.ToDouble(item.AwayTeamBonus)))
            {
                awayWin = true;
            }
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @if (homeWin)
                    {
                        <strong>@Html.DisplayFor(modelItem => item.HomeTeam.Name) <i class="fas fa-trophy"></i></strong>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.HomeTeam.Name)
                    }
                </td>
                <td>
                    @if (item.HomeTeamScore.HasValue)
                    {
                        @(@Convert.ToDouble(item.HomeTeamScore) + @Convert.ToDouble(item.HomeTeamBonus))
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.HomeTeamScore)
                    }
                </td>
                <td>
                    @if (item.HomeTeamScore.HasValue)
                    {
                        @(@Convert.ToDouble(item.AwayTeamScore) + @Convert.ToDouble(item.AwayTeamBonus))
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.AwayTeamScore)
                    }
                </td>
                <td>
                    @if (awayWin)
                    {
                        <strong>@Html.DisplayFor(modelItem => item.AwayTeam.Name) <i class="fas fa-trophy"></i></strong>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.AwayTeam.Name)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Venue.Name)
                </td>
                <td>
                    <small>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin") || User.IsInRole("Captain"))
                            {
                                if (item.Approved == false)
                                {
                                    if (!item.CaptainResultID.HasValue && !item.HomeTeamScore.HasValue)
                                    {
                                        <a asp-controller="Matches" asp-action="Create" asp-route-id="@item.ID">Add Result</a> @:|
                                    }
                                    else
                                    {
                                        if (item.CaptainResultID != ViewBag.CaptainID)
                                        {
                                            if (User.IsInRole("Admin"))
                                            {
                                                <a asp-controller="Matches" asp-action="Edit" asp-route-id="@item.ID">Edit</a> @:|
                                            }
                                            <a asp-action="ApproveResult" asp-route-id="@item.ID">Approve Result</a> @:|
                                        }
                                        else if (item.CaptainResultID == ViewBag.CaptainID)
                                        {
                                            <a asp-controller="Matches" asp-action="Edit" asp-route-id="@item.ID">Edit</a> @:|
                                        }
                                        else if (User.IsInRole("Admin"))
                                        {
                                            <a asp-controller="Matches" asp-action="Edit" asp-route-id="@item.ID">Edit</a> @:|
                                        }
                                    }
                                }
                            }
                        }
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                if (!item.Approved)
                                {
                                    @:|
                                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                                }

                            }

                        }

                    </small>
                </td>
            </tr>
            homeWin = false;
            awayWin = false;
        }
    </tbody>
</table>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.5/css/fixedHeader.bootstrap.min.css"/>
<link rel="stylesheet" href=" https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css"/>
@section scripts{
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script src=" https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#indxFix').DataTable({
                "order": [[0, "asc"]],
                responsive: true
            });
        });
    </script>

}